# Generated by Django 5.0.4 on 2024-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fontfamilies',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='screensides',
            options={'ordering': ['-created_at']},
        ),
    ]
