# Generated by Django 5.0.4 on 2024-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_rename_bot_owner_chatbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltype',
            name='default_api_key',
            field=models.CharField(max_length=100, null=True, verbose_name='Chave'),
        ),
    ]
