# Generated by Django 5.0.4 on 2024-04-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_modeltype_default_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='model',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chatbots.modeltype',
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='search',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chatbots.searchtype',
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='tone',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chatbots.tonetype',
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chatbots.bottype',
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='voice',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chatbots.voicetype',
            ),
        ),
    ]
