# Generated by Django 5.0.4 on 2024-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_alter_chatbot_model_alter_chatbot_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Privado'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
