# Generated by Django 5.0.4 on 2024-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_chatbot_is_active_chatbot_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltype',
            name='credits_cost',
            field=models.IntegerField(default=1, verbose_name='Custo por crédito'),
        ),
    ]
