# Generated by Django 5.0.4 on 2024-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0006_modeltype_credits_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Privado'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='credits_cost',
            field=models.IntegerField(default=1, verbose_name='Créditos por mensagem'),
        ),
    ]
