# Generated by Django 5.0.4 on 2024-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0008_chatbot_color_chatbot_font_chatbot_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='color',
            field=models.CharField(default='#536cbc', max_length=7, verbose_name='Color'),
        ),
    ]
